# Proyecto: Descompocisión de matrices en términos de sus eigenvalores y eigenvectores

In [2]:
%matplotlib inline

import numpy as np 

import matplotlib.pyplot as plt 

# Importamos nuestra función para graficar. 
%run './Funciones_auxiliares/my_functions.ipynb'

## Descomposición 1:

Si $A$ es cuadrada con $det(A)\neq 0$, se puede descomponer como:

$A = V * L * V ^{-1}$, 

donde $V$ es una matriz de Eigenvectores de $A$

y $L$ es una matriz diaginal de los Eigenvalores de $A$


In [3]:
# Matriz:
A = np.array([ [3,2,0,1], [1,0,4,1],[0,1,5,7],[7,4,-1,0] ])
print('A = \n',A)

A = 
 [[ 3  2  0  1]
 [ 1  0  4  1]
 [ 0  1  5  7]
 [ 7  4 -1  0]]


In [7]:
# Obtenemos los Eigenvalores y Eigenvectores:
eigenvals, eigenvecs=np.linalg.eig(A)

#print('Eigenvalores = ',eigenvals)

#print('\nEigenvectores = ',eigenvecs)


In [8]:
# Matriz de eigenvectores:
V = eigenvecs

# Matriz diagonal de eigenvalores:
L = np.diag(eigenvals)

# Matriz de eigenvectores inversa:
iV=np.linalg.inv(V)

### Obs: Como la matriz $V*L*V^{-1}$ es compleja, solo nos quedamos con la parte real

In [16]:
# Comprobación: A = V*L*iV
AA = np.dot( np.dot(V,L) , iV)
AA = np.real(AA) # <-- obtenemos la parte real

print('V*L*iV = \n',AA)
print('\nA = \n',A)

V*L*iV = 
 [[ 3.00000000e+00  2.00000000e+00  1.43606808e-15  1.00000000e+00]
 [ 1.00000000e+00  1.74236429e-16  4.00000000e+00  1.00000000e+00]
 [ 2.14544355e-16  1.00000000e+00  5.00000000e+00  7.00000000e+00]
 [ 7.00000000e+00  4.00000000e+00 -1.00000000e+00 -1.20113296e-15]]

A = 
 [[ 3  2  0  1]
 [ 1  0  4  1]
 [ 0  1  5  7]
 [ 7  4 -1  0]]
