# Proyecto: Descompocisión de matrices en términos de sus eigenvalores y eigenvectores

In [1]:
%matplotlib inline

import numpy as np 

import matplotlib.pyplot as plt 

# Importamos nuestra función para graficar. 
%run './Funciones_auxiliares/my_functions.ipynb'

## Descomposición 1:

Si $A$ es cuadrada con $det(A)\neq 0$, se puede descomponer como:

$A = V * L * V ^{-1}$, 

donde $V$ es una matriz de Eigenvectores de $A$

y $L$ es una matriz diaginal de los Eigenvalores de $A$


In [2]:
# Matriz:
A = np.array([ [3,2],[4,1] ])
print('A = \n',A)

A = 
 [[3 2]
 [4 1]]


In [3]:
# Obtenemos los Eigenvalores y Eigenvectores:
eigenvals, eigenvecs=np.linalg.eig(A)

# Extraemos los eigenvalores:
lam1=eigenvals[0]
lam2=eigenvals[1]

# Extraemos los eigenvectores:
v1=eigenvecs[:,0]
v2=eigenvecs[:,1]

print('l1 = ',lam1)
print('v1 = ',v1)
print('\nl2 = ',lam2)
print('v2 = ',v2)


l1 =  5.0
v1 =  [0.70710678 0.70710678]

l2 =  -1.0
v2 =  [-0.4472136   0.89442719]


In [4]:
# Matriz de eigenvectores:
V = eigenvecs

# Matriz diagonal de eigenvalores:
L = np.diag(eigenvals)

# Matriz de eigenvectores inversa:
iV=np.linalg.inv(V)

In [5]:
# Comprobación: A = V*L*iV
AA = np.dot( np.dot(V,L) , iV)

print('V*L*iV = \n',AA)
print('\nA = \n',A)

V*L*iV = 
 [[3. 2.]
 [4. 1.]]

A = 
 [[3 2]
 [4 1]]


## Descomposición 2:

Si $A$ es real y simétrica, ie. $A=A^{T}$, se puede descomponer como:

$A = V * L * V ^{T}$, 

donde $V$ es una matriz de Eigenvectores de $A$

y $L$ es una matriz diaginal de los Eigenvalores de $A$


In [6]:
# Matriz A:
A = np.array([ [3,2], [2,3] ])
A

array([[3, 2],
       [2, 3]])

In [7]:
# Obtenemos los Eigenvalores y Eigenvectores:
eigenvals, eigenvecs=np.linalg.eig(A)

# Extraemos los eigenvalores:
lam1=eigenvals[0]
lam2=eigenvals[1]

# Extraemos los eigenvectores:
v1=eigenvecs[:,0]
v2=eigenvecs[:,1]

print('l1 = ',lam1)
print('v1 = ',v1)
print('\nl2 = ',lam2)
print('v2 = ',v2)

l1 =  5.0
v1 =  [0.70710678 0.70710678]

l2 =  1.0000000000000004
v2 =  [-0.70710678  0.70710678]


In [8]:
# Matriz de eigenvectores:
V = eigenvecs

# Matriz diagonal de eigenvalores:
L = np.diag(eigenvals)

# Matriz de eigenvectores TRANSPUESTA:
Vt=V.T

In [9]:
# Comprobación: A = V*L*Vt
AA = np.dot( np.dot(V,L) , Vt)

print('V*L*iV = \n',AA)
print('\nA = \n',A)

V*L*iV = 
 [[3. 2.]
 [2. 3.]]

A = 
 [[3 2]
 [2 3]]
