# Proyecto: Descompocisión de matrices en términos de sus valores singulares

In [1]:
import numpy as np 

import matplotlib.pyplot as plt 



In [2]:
# Matriz
A = np.array([ [1,2,3], [3,4,5] ])
print('A =\n',A)

A =
 [[1 2 3]
 [3 4 5]]


In [3]:
# Obtenemos los valores singulares:

U,D,V = np.linalg.svd(A)
D = np.diag(D)
# Cada matriz represnta una serie de transformaciones que definene la matriz original:
# U <-- Primer rotación de la base
# D <-- Escalamiento (Valores singulaes)
# V <-- Segunda rotación de la base


print('U = \n',U)

print('\nD = \n', D)

print('\nV = \n',V)

U = 
 [[-0.46410668 -0.88577931]
 [-0.88577931  0.46410668]]

D = 
 [[7.97638869 0.        ]
 [0.         0.61418515]]

V = 
 [[-0.39133557 -0.5605708  -0.72980603]
 [ 0.8247362   0.13817999 -0.54837623]
 [ 0.40824829 -0.81649658  0.40824829]]
