## Proyecto: Aplicación de la descomposición e valores singulares para resolver sistemas lineales con más ecuaciones que incógnitas

### Dado el sistema $Ax = b$, donde, $A$ es una matriz de $m \times n$ con $m > n$,

### la solución esta dada por: $x = A_{p}^{-1} b$, 

### donde $A_{p}^{-1}$ se conoce como "Pseudo inversa de Moore-Penrose".

### Podemos obtener $A_{p}^{-1}$ mediante `np.linalg.pinv(A)` 

### o bien podemos usar descomposición en valores singulares para calcular $A_{p}^{-1}$

In [8]:
import numpy as np

np.set_printoptions(suppress=True)# <-- permite imprimir valores muy cercanos a cero, redondeados a cero

In [9]:
# Matriz de 'm x n' con 'm > n'
#A = np.array([ [2,3],[5,7],[11,13] ])
A = np.array([ [2,3,1],[1,5,7],[0,11,13], [3,0,1] , [1,8,-1] ])

# obtenemos numero de renglones y comumnas de A:
m,n = A.shape

print('A = \n', A)
print('\nA tiene ',m, 'renglones y ',n,' columnas')

A = 
 [[ 2  3  1]
 [ 1  5  7]
 [ 0 11 13]
 [ 3  0  1]
 [ 1  8 -1]]

A tiene  5 renglones y  3  columnas


In [10]:
# Obtenemos la descomposicion SVD:
U,D,V = np.linalg.svd(A)

print('U = \n',U)

print('\nD = \n', D)

print('\nV = \n',V)


U = 
 [[-0.14772131 -0.246021   -0.44053949 -0.83945971 -0.13742064]
 [-0.42966486  0.18655837 -0.20854037  0.26410339 -0.8169115 ]
 [-0.85356595  0.21923601  0.1971208  -0.08637476  0.4207654 ]
 [-0.044065    0.03012849 -0.84539252  0.38210599  0.36940093]
 [-0.25109752 -0.92503918  0.0942907   0.26849807 -0.01645   ]]

D = 
 [19.85417065  6.92471404  3.58611814]

V = 
 [[-0.05582706 -0.70461235 -0.70739294]
 [-0.16464757 -0.69230129  0.70257391]
 [-0.9847713   0.15569317 -0.07736356]]


In [11]:
# Construimos la pseudo diagonal 'D_pse':

# Obtenemos el iverso de los valores singulares:
D_inv = 1/D
# convertimos a matriz diagonal:
D_inv = np.diag(D_inv) #<-- matriz de 'n x n'
print('inv(D) = \n',D_inv)

# Matriz pseudo diagonal de 'n x m' (recodemos que 'm > n')
D_pse = np.zeros([n,m])
D_pse[0:n , 0:n] = D_inv
print('\nDpse = \n',D_pse)

inv(D) = 
 [[0.05036725 0.         0.        ]
 [0.         0.1444103  0.        ]
 [0.         0.         0.27885305]]

Dpse = 
 [[0.05036725 0.         0.         0.         0.        ]
 [0.         0.1444103  0.         0.         0.        ]
 [0.         0.         0.27885305 0.         0.        ]]


In [12]:
# Construcción de la pseudo inversa de A:

A_pse = np.dot( V.T , np.dot(D_pse , U.T) )

print('\nApse = \n',A_pse)


Apse = 
 [[ 0.12723997  0.05403893 -0.05694328  0.23155782 -0.00319231]
 [ 0.01071235 -0.0124566   0.01693242 -0.03815142  0.10548617]
 [-0.01019401  0.03873558  0.04840302  0.02286452 -0.08694114]]


In [13]:
# Comprobación con la función 'np.linalg.pinv':
A_pse2=np.linalg.pinv(A)
A_pse2


array([[ 0.12723997,  0.05403893, -0.05694328,  0.23155782, -0.00319231],
       [ 0.01071235, -0.0124566 ,  0.01693242, -0.03815142,  0.10548617],
       [-0.01019401,  0.03873558,  0.04840302,  0.02286452, -0.08694114]])

In [14]:
np.dot(A_pse,A)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0.,  0.,  1.]])